server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://120.24.144.173:3306/quotations_test?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123lyl
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      table-underline: true
      id-type: auto


file:
  upload:
    dir: usr/file/upload